[package]
name = "rusense-gui"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "rusense-gui"
path = "src/main.rs"

[dependencies]
rusense-core = { path = "../core" }
tauri = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = "2"
